const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("Deploying contracts to Mantle Sepolia...\n");
  
  // Deploy RealEstateIDO (property listings)
  console.log("1. Deploying RealEstateIDO...");
  const RealEstateIDO = await hre.ethers.getContractFactory("RealEstateIDO");
  const realEstateIDO = await RealEstateIDO.deploy();
  await realEstateIDO.waitForDeployment();
  const idoAddress = await realEstateIDO.getAddress();
  console.log("   RealEstateIDO deployed to:", idoAddress);
  
  // Deploy PropertyToken (demo tokenized property)
  console.log("\n2. Deploying PropertyToken (Demo Property)...");
  const PropertyToken = await hre.ethers.getContractFactory("PropertyToken");
  
  // Demo property parameters
  const propertyToken = await PropertyToken.deploy(
    "Graso Lagos Property",           // name
    "GLP",                              // symbol
    "Lagos Beachfront Villa",           // title
    "Luxury beachfront property with ocean views, 5 bedrooms, modern amenities", // description
    "Victoria Island, Lagos, Nigeria",  // location
    "QmDemo123",                        // imageHash (IPFS)
    hre.ethers.parseEther("500000"),    // valuation (500,000 MNT)
    hre.ethers.parseEther("10000"),     // totalSupply (10,000 tokens)
    hre.ethers.parseEther("50"),        // pricePerToken (50 MNT each)
    800                                 // yieldRate (8% annual)
  );
  await propertyToken.waitForDeployment();
  const tokenAddress = await propertyToken.getAddress();
  console.log("   PropertyToken deployed to:", tokenAddress);
  
  // Get ABIs from artifacts
  const realEstateIDOArtifact = await hre.artifacts.readArtifact("RealEstateIDO");
  const propertyTokenArtifact = await hre.artifacts.readArtifact("PropertyToken");
  
  // Create contract export data
  const contractData = {
    network: hre.network.name,
    chainId: hre.network.config.chainId || 5003,
    deployedAt: new Date().toISOString(),
    contracts: {
      RealEstateIDO: {
        address: idoAddress,
        abi: realEstateIDOArtifact.abi,
      },
      PropertyToken: {
        address: tokenAddress,
        abi: propertyTokenArtifact.abi,
      },
    },
  };
  
  // Export to frontend public/contract directory
  const frontendContractDir = path.join(__dirname, "../../public/contract");
  
  // Create directory if it doesn't exist
  if (!fs.existsSync(frontendContractDir)) {
    fs.mkdirSync(frontendContractDir, { recursive: true });
  }
  
  // Write contracts.js (ES module export)
  const contractsJsContent = `// Auto-generated by deploy script
// Deployed at: ${new Date().toISOString()}
// Network: ${hre.network.name}

export const NETWORK = "${hre.network.name}";
export const CHAIN_ID = ${hre.network.config.chainId || 5003};
export const DEPLOYED_AT = "${new Date().toISOString()}";

export const RealEstateIDO = {
  address: "${idoAddress}",
  abi: ${JSON.stringify(realEstateIDOArtifact.abi, null, 2)}
};

export const PropertyToken = {
  address: "${tokenAddress}",
  abi: ${JSON.stringify(propertyTokenArtifact.abi, null, 2)}
};

// Export all contracts
export const contracts = {
  RealEstateIDO,
  PropertyToken,
};

export default contracts;
`;

  fs.writeFileSync(
    path.join(frontendContractDir, "contracts.js"),
    contractsJsContent
  );
  console.log("\n3. Exported contracts to public/contract/contracts.js");
  
  // Also write JSON version for flexibility
  fs.writeFileSync(
    path.join(frontendContractDir, "contracts.json"),
    JSON.stringify(contractData, null, 2)
  );
  console.log("   Exported JSON to public/contract/contracts.json");
  
  // Summary
  console.log("\n========================================");
  console.log("Deployment Complete!");
  console.log("========================================");
  console.log("RealEstateIDO:", idoAddress);
  console.log("PropertyToken:", tokenAddress);
  console.log("Network:", hre.network.name);
  console.log("========================================\n");
  
  console.log("✅ Contracts auto-exported to: public/contract/");
  console.log("   - contracts.js  (ES module)");
  console.log("   - contracts.json (JSON data)");
  console.log("\nView contracts on explorer:");
  console.log(`   https://explorer.sepolia.mantle.xyz/address/${idoAddress}`);
  console.log(`   https://explorer.sepolia.mantle.xyz/address/${tokenAddress}`);
  
  return { idoAddress, tokenAddress };
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
